# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-06 18:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Affiliation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(null=True)),
                ('end_date', models.DateField(null=True)),
                ('confidence', models.FloatField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Affiliation_instance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('au_fname', models.CharField(max_length=45, null=True)),
                ('au_lname', models.CharField(max_length=45, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Author_Identity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('confidence', models.FloatField(null=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='django-tethne.Author')),
            ],
        ),
        migrations.CreateModel(
            name='Author_Instance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('au_fname', models.CharField(max_length=45, null=True)),
                ('au_lname', models.CharField(max_length=45, null=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='django-tethne.Author')),
            ],
        ),
        migrations.CreateModel(
            name='Citation_Indentity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('confidence', models.FloatField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Citation_Instance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('literal', models.CharField(max_length=45, null=True)),
                ('journal', models.CharField(max_length=45, null=True)),
                ('first_author', models.CharField(max_length=45, null=True)),
                ('date', models.DateField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Corpus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_created=True, auto_now=True)),
                ('length', models.IntegerField(null=True)),
                ('label', models.CharField(max_length=10, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Institution',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=45, null=True)),
                ('addressLine1', models.CharField(max_length=50, null=True)),
                ('addressLine2', models.CharField(max_length=50, null=True)),
                ('state', models.CharField(max_length=45, null=True)),
                ('city', models.CharField(max_length=45, null=True)),
                ('zip', models.CharField(max_length=45, null=True)),
                ('country', models.CharField(max_length=45, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Institution_Identity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('confidence', models.FloatField(null=True)),
                ('institution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='django-tethne.Institution')),
            ],
        ),
        migrations.CreateModel(
            name='Institution_Instance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department', models.CharField(max_length=45, null=True)),
                ('name', models.CharField(max_length=45, null=True)),
                ('addressLine1', models.CharField(max_length=50, null=True)),
                ('addressLine2', models.CharField(max_length=50, null=True)),
                ('state', models.CharField(max_length=45, null=True)),
                ('city', models.CharField(max_length=45, null=True)),
                ('zip', models.CharField(max_length=45, null=True)),
                ('country', models.CharField(max_length=45, null=True)),
                ('institution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='django-tethne.Institution')),
            ],
        ),
        migrations.CreateModel(
            name='Paper',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pub_date', models.DateField(null=True)),
                ('is_collaborated', models.BooleanField()),
                ('title', models.TextField(null=True)),
                ('volume', models.CharField(max_length=40, null=True)),
                ('issue', models.CharField(max_length=40, null=True)),
                ('abstract', models.TextField(null=True)),
                ('corpus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='django-tethne.Corpus')),
            ],
        ),
        migrations.CreateModel(
            name='Source',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_value', models.CharField(max_length=35, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='institution_instance',
            name='paper',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='django-tethne.Paper'),
        ),
        migrations.AddField(
            model_name='institution_identity',
            name='institution_instance',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='django-tethne.Institution_Instance'),
        ),
        migrations.AddField(
            model_name='corpus',
            name='source',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='django-tethne.Source'),
        ),
        migrations.AddField(
            model_name='citation_instance',
            name='paper',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='django-tethne.Paper'),
        ),
        migrations.AddField(
            model_name='citation_indentity',
            name='citation_instance',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='django-tethne.Citation_Instance'),
        ),
        migrations.AddField(
            model_name='author_instance',
            name='paper',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='django-tethne.Paper'),
        ),
        migrations.AddField(
            model_name='author_identity',
            name='author_instance',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='django-tethne.Author_Instance'),
        ),
        migrations.AddField(
            model_name='affiliation_instance',
            name='author_instance',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='django-tethne.Author_Instance'),
        ),
        migrations.AddField(
            model_name='affiliation_instance',
            name='institution_instance',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='django-tethne.Institution_Instance'),
        ),
        migrations.AddField(
            model_name='affiliation',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='django-tethne.Author'),
        ),
        migrations.AddField(
            model_name='affiliation',
            name='institution',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='django-tethne.Institution'),
        ),
    ]
